# Exercise 1 - Matrix warmup

### Basics

1. Create two arrays, a and b which each have the integers 0, 1, 2 ..., 1e7 - 1. 

2. Create a function that uses a for-loop or equivalent to return a new array, which contains the element-wise sum of a and b.

3. Now create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g np.array in NumPy) and add the arrays together using your function. Don’t use loops, instead, find out how to add the two arrays together directly. What do you notice?

In [10]:
# 1.
a = b = [i for i in range(10**7)]
a[10**7-3:]

[9999997, 9999998, 9999999]

In [11]:
# 2.
def add_with_for(a, b):
    c = []
    for i in range(len(a)):
        c.append(a[i] + b[i])
    return c

c = add_with_for(a, b)
c[:10]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
# 3.
import numpy as np

In [13]:
na = nb = np.arange(10**7)

def add_with_np(a, b):
    return np.add(a,b)

nc = add_with_np(na,nb)
nc[:10]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

We can see that numpy is much faster as it is more efficient.

### Array manipulation

**(a)** Create the following array (hint: reshape)

``
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
``

**(b)** Create the following array

``
array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])
       ``
       
**(c)** Create the following array

``
array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])
      ``

**(d)** Create the following array

``
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
       ``
       
**(e)** Call the last two matrices C and D, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is, calculate both det(CD) and det(C) * det(D), and show that they are the same. Why does this hold in this instance? Does it hold in general?

In [14]:
# a
a = np.arange(100).reshape((10, 10))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [15]:
# b
b = np.arange(2, dtype = float)
b = np.tile(b, 50).reshape(10,10)
print(b)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


In [16]:
# c
c = np.ones(100).reshape(10,10)
np.fill_diagonal(c,0)
print(c)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


In [17]:
# d
d = np.ones(100).reshape(10,10)
np.fill_diagonal(d,0)
d = np.flipud(d)
print(d)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
# e
detC = np.linalg.det(c)
detD = np.linalg.det(d)

prodDetCD = detC * detD

prodCD = c.dot(d)
detProdCD = np.linalg.det(prodCD)

print("Prod of determinants: ", prodDetCD)
print("Determinant of products: ", detProdCD)

Prod of determinants:  -81.0
Determinant of products:  -81.00000000000017


It gives the same result (except an error of calculation). This holds in general for square matrices of the same order.

### Slicing 

1. Load the Boston housing dataset. The data should be a matrix of shape (506, 13), that is, it has 506 rows and 13 columns. Use the shape attribute of numpy arrays to verify this.

2. Select rows where the Crime feature (CRIM) is higher than 1. The first few row numbers should be 16, 20, 22 (zero-indexed). How many are there? (hint. np.where)

3. Select the rows where the pupil-to-teach ratio is between 16% and 18% (exclusive). There should be 100 of these.

4. Find the mean nitric oxides concentration for homes whose median price is more than $25000 (the target variable). It should be around 0.492.

In [19]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [20]:
# 1.
bostonBunch = datasets.load_boston()
boston = pd.DataFrame(bostonBunch.data, columns = bostonBunch.feature_names)
print("Shape:", np.shape(boston))
print()
print(boston[:5])

Shape: (506, 13)

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33  


In [21]:
# 2.
crim1 = np.where(boston['CRIM'] > 1)
print(crim1[0][:3])
print("There are", len(crim1[0]), "rows.")

# print(boston[boston['CRIM']>1])

[16 20 22]
There are 174 rows.


In [22]:
# 3.
ptt = boston[(boston['PTRATIO']>16) & (boston['PTRATIO']<18)]
print("There are", len(ptt), "rows.")

There are 100 rows.


In [23]:
# 4.
boston['MED'] = bostonBunch.target # adding the target to the dataset
med25 = boston[boston['MED']>25]
meanNOX = np.mean(med25['NOX'])
print("The mean is:",meanNOX)

The mean is: 0.4921201612903226


# Exercise 2 - Text data

Download the automotive 5-core dataset from [here](http://jmcauley.ucsd.edu/data/amazon/). 

**(a)** Open the json file in your favorite environment.

**(b)** Access the reviewText field, and downcase the contents.

**(c)** Remove all punctuation, as well as the stop-words. You can find a stop-word list for English e.g [here](http://xpo6.com/download-stop-word-list/).

**(d)** Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for python the popular natural language toolkit nltk has an easy-to-use stemmer.

**(e)** Filter the data by selecting reviews where the field overall is 4 or 5, and store the review texts in file pos.txt. Similarly, select reviews with rating 1 or 2 and store the reviews in file neg.txt. (Ignore the reviews with overall rating 3.) Each line in the two files should contain exactly one preprocessed review text without the rating.

In [24]:
import json

In [25]:
# a
data = []
for line in open('Automotive_5.json', 'r'):
    data.append(json.loads(line))
    
print(data[:2])

[{'reviewerID': 'A3F73SC1LY51OO', 'asin': 'B00002243X', 'reviewerName': 'Alan Montgomery', 'helpful': [4, 4], 'reviewText': "I needed a set of jumper cables for my new car and these had good reviews and were at a good price.  They have been used a few times already and do what they are supposed to - no complaints there.What I will say is that 12 feet really isn't an ideal length.  Sure, if you pull up front bumper to front bumper they are plenty long, but a lot of times you will be beside another car or can't get really close.  Because of this, I would recommend something a little longer than 12'.Great brand - get 16' version though.", 'overall': 5.0, 'summary': 'Work Well - Should Have Bought Longer Ones', 'unixReviewTime': 1313539200, 'reviewTime': '08 17, 2011'}, {'reviewerID': 'A20S66SKYXULG2', 'asin': 'B00002243X', 'reviewerName': 'alphonse', 'helpful': [1, 1], 'reviewText': 'These long cables work fine for my truck, but the quality seems a little on the shabby side. For the money

In [26]:
# b
for i in range(len(data)):
    data[i]['reviewText'] = data[i]['reviewText'].lower()
print(data[1]['reviewText'])

these long cables work fine for my truck, but the quality seems a little on the shabby side. for the money i was not expecting 200 dollar snap-on jumper cables but these seem more like what you would see at a chinese knock off shop like harbor freight for 30 bucks.


In [27]:
# c
f = open('stop-word-list.txt', 'r')
stopwords = f.read().splitlines()
print(stopwords)

['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant', 'co', 'computer', 'con', 'could', 'couldnt', 'cry', 'de', 'describe', 'detail', 'do', 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'except', 'few', 'fifteen', 'fify', 'fill', 'find', 'fire', 'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', '

In [28]:
import string
exclude = string.punctuation

for i in range(len(data)):
    data[i]['reviewText'] = ''.join(char for char in data[i]['reviewText'] if char not in exclude)

print(data[0]['reviewText'])

i needed a set of jumper cables for my new car and these had good reviews and were at a good price  they have been used a few times already and do what they are supposed to  no complaints therewhat i will say is that 12 feet really isnt an ideal length  sure if you pull up front bumper to front bumper they are plenty long but a lot of times you will be beside another car or cant get really close  because of this i would recommend something a little longer than 12great brand  get 16 version though


In [29]:
for i in range(len(data)):
    data[i]['reviewText'] = ' '.join(filter(lambda x: x not in stopwords, data[i]['reviewText'].split()))

print(data[0]['reviewText'])

needed set jumper cables new car good reviews good price used times supposed complaints therewhat say 12 feet really isnt ideal length sure pull bumper bumper plenty long lot times car really close recommend little longer 12great brand 16 version


In [30]:
# d
import nltk
from nltk.stem import *

In [31]:
stemmer = PorterStemmer()
for i in range(len(data)):
    data[i]['reviewText'] = ' '.join(map(lambda x: stemmer.stem(x), data[i]['reviewText'].split()))

print(data[0]['reviewText'])

need set jumper cabl new car good review good price use time suppos complaint therewhat say 12 feet realli isnt ideal length sure pull bumper bumper plenti long lot time car realli close recommend littl longer 12great brand 16 version


In [32]:
# e
pos = open('pos.txt', 'w')
neg = open('neg.txt', 'w')
for i in range(len(data)):
    if data[i]['overall'] > 3:
        pos.write(data[i]['reviewText'])
        pos.write('\n')
    elif data[i]['overall'] < 3:
        neg.write(data[i]['reviewText'])
        neg.write('\n')